version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    networks:
      - api
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
  # main:
  #   build:
  #     context: .
  #     target: development
  #   container_name: main
  #   ports:
  #     - 3000:3000
  #   restart: always
  #   command: npm run start:dev
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   env_file:
  #     - .env
  #   networks:
  #     - api
  #   depends_on:
  #     - postgres
networks:
  api:
volumes:
  postgres:
    name: nest-prisma-docker-db
